[package]
name = "space_station_god_game_proto_rust"
version = "0.1.0"
authors = ["Myles Grant <myles@mylesgrant.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5"
